kind: pipeline
name: default
steps:
- name: build
  image: node:8
  commands:
  - npm install
  - npm test
  - npm run build:transpile
- name: npm
  image: plugins/npm
  settings:
    token:
      from_secret: npm_token
  when:
    event: tag
trigger:
  event: [push, tag]